
    # Step 1
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1
    t_window_SHGC = 1
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1
    t_boiler_eff = 1
    t_waterHeater_eff = 1
    t_chiller_eff = 1
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 2
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 0.8
    t_ext_floor_conductivity = 1.5
    t_window_U = 1
    t_window_SHGC = 1
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1
    t_boiler_eff = 1
    t_waterHeater_eff = 1
    t_chiller_eff = 1
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 3
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1
    t_boiler_eff = 1
    t_waterHeater_eff = 1
    t_chiller_eff = 1
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 4
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1.2
    t_EPD = 1.2
    t_occ_density = 1
    t_boiler_eff = 1
    t_waterHeater_eff = 1
    t_chiller_eff = 1
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 5
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1.1
    t_EPD = 1.1
    t_occ_density = 1
    t_boiler_eff = 1
    t_waterHeater_eff = 1
    t_chiller_eff = 1
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 6
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 1
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 7
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 8
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 1
    t_OA_per_person = 1

    # Step 9
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 1.5
    t_OA_per_person = 1

    # Step 10
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 2
    t_OA_per_person = 1

    # Step 11
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 2
    t_OA_per_person = 1.5

    # Step 12
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 2.5
    t_OA_per_person = 1.5

    # Step 13
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 2.5
    t_OA_per_person = 1.3

    # Step 14
    t_ext_wall_thickness = 0.8
    t_ext_wall_conductivity = 1.5
    t_ext_floor_thickness = 1
    t_ext_floor_conductivity = 1
    t_window_U = 1.2
    t_window_SHGC = 0.8
    t_LPD = 1
    t_EPD = 1
    t_occ_density = 1.5
    t_boiler_eff = 0.9
    t_waterHeater_eff = 0.9
    t_chiller_eff = 0.9
    t_infiltration = 2.5
    t_OA_per_person = 1.4