# Step 1
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 1.5
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1
t_EPD = 1
t_occ_density = 1
n_boiler_eff = 0.78
n_waterHeater_eff = 0.78
t_infiltration = 1

# Step 2
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1
t_EPD = 1
t_occ_density = 1
n_boiler_eff = 0.78
n_waterHeater_eff = 0.78
t_infiltration = 1

# Step 3
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.5
t_EPD = 1.5
t_occ_density = 1
n_boiler_eff = 0.78
n_waterHeater_eff = 0.78
t_infiltration = 1

# Step 4
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.2
t_EPD = 1.2
t_occ_density = 1
n_boiler_eff = 0.78
n_waterHeater_eff = 0.78
t_infiltration = 1

# Step 5
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1
n_boiler_eff = 0.78
n_waterHeater_eff = 0.78
t_infiltration = 1

# Step 6
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1
n_boiler_eff = 0.75
n_waterHeater_eff = 0.75
t_infiltration = 1

# Step 7
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1

# Step 8
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1.5
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1

# Step 9
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1.5
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 2

# Step 10
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 1
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1.5
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1.5

# Step 11
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 0.8
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 1.5
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1.5

# Step 12
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 0.8
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 2
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1.5

# Step 13
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 0.8
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 3
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1.5

# Step 14
t_ext_wall_thickness = 0.8
t_ext_wall_conductivity = 2
t_ext_floor_thickness = 1
t_ext_floor_conductivity = 0.8
t_LPD = 1.1
t_EPD = 1.1
t_occ_density = 
n_boiler_eff = 0.7
n_waterHeater_eff = 0.7
t_infiltration = 1.5